"""
ECA (Event Correlation Agent) Contract

Defines how ECA listens to Kafka topics, detects anomalies,
generates tickets, and feeds mitigation tasks back to the system.
"""

from typing import Dict, List, Any, Optional
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
import uuid


# ============================================================================
# EVENT TYPES & SCHEMAS
# ============================================================================

class EventCategory(Enum):
    """Event categories ECA subscribes to."""
    SYSLOG_EVENT = "syslog-events"
    AGENT_ERROR = "agent-errors"
    DATA_UPDATE = "data-updates"
    PERFORMANCE_ALERT = "performance-alerts"
    SECURITY_AUDIT = "security-audits"


class EventSeverity(Enum):
    """Severity levels for events."""
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


class AnomalyType(Enum):
    """Types of anomalies ECA can detect."""
    MCP_TIMEOUT = "mcp_timeout"
    MCP_FAILURE = "mcp_failure"
    MISSING_DATA = "missing_data"
    DATA_QUALITY_ISSUE = "data_quality_issue"
    SPECIALIST_CRASH = "specialist_crash"
    CREDENTIAL_DENIED = "credential_denied"
    RATE_LIMIT_EXCEEDED = "rate_limit_exceeded"
    LATENCY_SPIKE = "latency_spike"
    INCONSISTENT_DATA = "inconsistent_data"


@dataclass
class KafkaEvent:
    """
    Event from Kafka that ECA processes.
    
    Format: JSON serialized to Kafka topic
    """
    
    event_id: str
    timestamp: float
    category: str                     # e.g., "agent-errors"
    severity: str                     # e.g., "error"
    
    # Source information
    source_agent: str                 # e.g., "geological_scout_001"
    job_id: Optional[str]             # EJMS job ID if applicable
    trace_id: Optional[str]           # OpenTelemetry trace ID
    request_id: Optional[str]         # User request ID
    
    # Event content
    message: str
    details: Dict[str, Any]           # Event-specific details
    
    # Metadata
    processed: bool = False           # Has ECA processed this?
    anomaly_detected: bool = False    # Did ECA flag as anomaly?


@dataclass
class DetectedAnomaly:
    """
    Anomaly detected by ECA's rule engine.
    """
    
    anomaly_id: str
    timestamp: float
    anomaly_type: str                 # e.g., "mcp_timeout"
    severity: str                     # e.g., "critical"
    
    # Root cause
    source_event_id: str              # Kafka event that triggered detection
    root_cause: str                   # Human-readable description
    affected_component: str           # e.g., "geological_mcp"
    affected_job: Optional[str]
    
    # Remediation
    auto_remediation_possible: bool
    suggested_remediation: List[str]  # e.g., ["retry_with_backoff", "failover_to_cached_data"]
    
    # Logging
    ticket_generated: bool = False
    ticket_id: Optional[str] = None


@dataclass
class MitigationTicket:
    """
    Ticket generated by ECA for sub-tasks and remediation.
    """
    
    ticket_id: str
    ticket_type: str                  # "retry", "fallback", "escalate", "refresh_data"
    priority: str                     # "low", "medium", "high", "critical"
    
    # Task definition
    title: str
    description: str
    related_anomaly_id: str
    related_job_id: Optional[str]
    
    # Execution
    target_agent: Optional[str]       # Which agent should handle this
    execution_steps: List[str]        # Procedural steps
    
    # Metadata
    created_at: float
    execute_by: Optional[float]       # Deadline or auto-execute time
    status: str = "pending"           # "pending", "assigned", "executing", "completed", "failed"


# ============================================================================
# KAFKA SUBSCRIPTIONS
# ============================================================================

class ECAKafkaSubscriptions:
    """
    Defines which Kafka topics ECA subscribes to and processes.
    """
    
    # Topic names
    TOPICS = {
        "syslog-events": {
            "description": "System logs from all components",
            "expected_volume": "high",
            "retention_hours": 24
        },
        "agent-errors": {
            "description": "Error events from specialist agents",
            "expected_volume": "medium",
            "retention_hours": 72
        },
        "data-updates": {
            "description": "Data refresh/update notifications",
            "expected_volume": "low",
            "retention_hours": 168  # 1 week
        },
        "performance-alerts": {
            "description": "Latency & performance metrics",
            "expected_volume": "medium",
            "retention_hours": 48
        },
        "security-audits": {
            "description": "Security events (credential usage, access denied)",
            "expected_volume": "low",
            "retention_hours": 365
        }
    }

    @staticmethod
    def get_subscriptions() -> List[str]:
        """Get all topics ECA subscribes to."""
        return list(ECAKafkaSubscriptions.TOPICS.keys())


# ============================================================================
# ANOMALY DETECTION RULES
# ============================================================================

class AnomalyDetectionRules:
    """
    Rule engine for detecting anomalies in events.
    """

    @staticmethod
    def apply_rules(event: KafkaEvent) -> Optional[DetectedAnomaly]:
        """
        Apply detection rules to incoming event.
        
        Returns:
            DetectedAnomaly if anomaly detected, None otherwise
        """
        
        # Rule 1: MCP Tool Timeout
        if event.category == "agent-errors" and "timeout" in event.message.lower():
            return AnomalyDetectionRules._create_mcp_timeout_anomaly(event)
        
        # Rule 2: Repeated Failures from Same MCP
        # (Would track in-memory state here)
        
        # Rule 3: Data Quality Issue
        if event.category == "data-updates" and event.details.get("anomaly_flag"):
            return AnomalyDetectionRules._create_data_quality_anomaly(event)
        
        # Rule 4: Credential Denied
        if "credential" in event.message.lower() and "denied" in event.message.lower():
            return AnomalyDetectionRules._create_credential_denied_anomaly(event)
        
        # Rule 5: Latency Spike (> 10s)
        if event.details.get("execution_time_ms", 0) > 10000:
            return AnomalyDetectionRules._create_latency_spike_anomaly(event)
        
        # No anomaly detected
        return None

    @staticmethod
    def _create_mcp_timeout_anomaly(event: KafkaEvent) -> DetectedAnomaly:
        """Create MCP timeout anomaly."""
        return DetectedAnomaly(
            anomaly_id=str(uuid.uuid4()),
            timestamp=datetime.now().timestamp(),
            anomaly_type=AnomalyType.MCP_TIMEOUT.value,
            severity=EventSeverity.WARNING.value,
            source_event_id=event.event_id,
            root_cause=f"MCP tool {event.details.get('mcp_tool')} timed out",
            affected_component=event.details.get("mcp_server", "unknown"),
            affected_job=event.job_id,
            auto_remediation_possible=True,
            suggested_remediation=["retry_with_exponential_backoff", "failover_to_cache", "escalate_to_human"]
        )

    @staticmethod
    def _create_data_quality_anomaly(event: KafkaEvent) -> DetectedAnomaly:
        """Create data quality anomaly."""
        return DetectedAnomaly(
            anomaly_id=str(uuid.uuid4()),
            timestamp=datetime.now().timestamp(),
            anomaly_type=AnomalyType.DATA_QUALITY_ISSUE.value,
            severity=EventSeverity.WARNING.value,
            source_event_id=event.event_id,
            root_cause=f"Data quality issue in {event.details.get('dataset')}",
            affected_component=event.source_agent,
            affected_job=event.job_id,
            auto_remediation_possible=False,
            suggested_remediation=["manual_review", "re-execute_data_collection", "escalate_to_human"]
        )

    @staticmethod
    def _create_credential_denied_anomaly(event: KafkaEvent) -> DetectedAnomaly:
        """Create credential denied anomaly."""
        return DetectedAnomaly(
            anomaly_id=str(uuid.uuid4()),
            timestamp=datetime.now().timestamp(),
            anomaly_type=AnomalyType.CREDENTIAL_DENIED.value,
            severity=EventSeverity.CRITICAL.value,
            source_event_id=event.event_id,
            root_cause="ACS denied credential request (permission denied)",
            affected_component="ACS",
            affected_job=event.job_id,
            auto_remediation_possible=False,
            suggested_remediation=["escalate_to_admin", "check_acs_policies", "audit_access"]
        )

    @staticmethod
    def _create_latency_spike_anomaly(event: KafkaEvent) -> DetectedAnomaly:
        """Create latency spike anomaly."""
        return DetectedAnomaly(
            anomaly_id=str(uuid.uuid4()),
            timestamp=datetime.now().timestamp(),
            anomaly_type=AnomalyType.LATENCY_SPIKE.value,
            severity=EventSeverity.WARNING.value,
            source_event_id=event.event_id,
            root_cause=f"Latency spike: {event.details.get('execution_time_ms')}ms (threshold: 10000ms)",
            affected_component=event.source_agent,
            affected_job=event.job_id,
            auto_remediation_possible=True,
            suggested_remediation=["increase_timeout", "check_system_resources", "investigate_mcp_server"]
        )


# ============================================================================
# TICKET GENERATION
# ============================================================================

class TicketGenerator:
    """
    Generates mitigation tickets based on detected anomalies.
    """

    @staticmethod
    def generate_ticket(anomaly: DetectedAnomaly) -> MitigationTicket:
        """
        Create a mitigation ticket for an anomaly.
        
        Maps anomaly type to ticket type & execution steps.
        """
        
        ticket_id = f"TKT_{uuid.uuid4().hex[:8]}"
        
        if anomaly.anomaly_type == AnomalyType.MCP_TIMEOUT.value:
            return TicketGenerator._generate_timeout_ticket(ticket_id, anomaly)
        
        elif anomaly.anomaly_type == AnomalyType.DATA_QUALITY_ISSUE.value:
            return TicketGenerator._generate_data_quality_ticket(ticket_id, anomaly)
        
        elif anomaly.anomaly_type == AnomalyType.CREDENTIAL_DENIED.value:
            return TicketGenerator._generate_credential_ticket(ticket_id, anomaly)
        
        elif anomaly.anomaly_type == AnomalyType.LATENCY_SPIKE.value:
            return TicketGenerator._generate_latency_ticket(ticket_id, anomaly)
        
        else:
            return TicketGenerator._generate_generic_ticket(ticket_id, anomaly)

    @staticmethod
    def _generate_timeout_ticket(ticket_id: str, anomaly: DetectedAnomaly) -> MitigationTicket:
        """Generate ticket for MCP timeout."""
        return MitigationTicket(
            ticket_id=ticket_id,
            ticket_type="retry",
            priority="high",
            title=f"Retry MCP query: {anomaly.affected_component}",
            description=f"MCP tool timed out. Retry with exponential backoff.\nAnomaly: {anomaly.root_cause}",
            related_anomaly_id=anomaly.anomaly_id,
            related_job_id=anomaly.affected_job,
            target_agent="orchestrator",  # Send back to control plane
            execution_steps=[
                "1. Log timeout event",
                "2. Wait 2 seconds (exponential backoff: 2^1)",
                "3. Retry MCP tool call",
                "4. On next failure: escalate to fallback data source"
            ],
            created_at=datetime.now().timestamp(),
            execute_by=datetime.now().timestamp() + 30  # Execute within 30 seconds
        )

    @staticmethod
    def _generate_data_quality_ticket(ticket_id: str, anomaly: DetectedAnomaly) -> MitigationTicket:
        """Generate ticket for data quality issue."""
        return MitigationTicket(
            ticket_id=ticket_id,
            ticket_type="escalate",
            priority="medium",
            title=f"Data quality issue: {anomaly.affected_component}",
            description=f"Manual review required.\n{anomaly.root_cause}",
            related_anomaly_id=anomaly.anomaly_id,
            related_job_id=anomaly.affected_job,
            target_agent=None,  # Manual intervention
            execution_steps=[
                "1. Review raw data from source",
                "2. Validate against schema",
                "3. Check for outliers or malformed records",
                "4. Decide: proceed with warnings or re-execute collection"
            ],
            created_at=datetime.now().timestamp(),
            execute_by=datetime.now().timestamp() + 900  # Execute within 15 minutes
        )

    @staticmethod
    def _generate_credential_ticket(ticket_id: str, anomaly: DetectedAnomaly) -> MitigationTicket:
        """Generate ticket for credential denied."""
        return MitigationTicket(
            ticket_id=ticket_id,
            ticket_type="escalate",
            priority="critical",
            title="Security: Credential access denied",
            description=f"ACS rejected credential request.\n{anomaly.root_cause}",
            related_anomaly_id=anomaly.anomaly_id,
            related_job_id=anomaly.affected_job,
            target_agent=None,  # Requires human admin
            execution_steps=[
                "1. Review ACS audit logs",
                "2. Check agent permissions/role",
                "3. Verify MCP server is properly registered",
                "4. If legitimate: update IAM policy and retry"
            ],
            created_at=datetime.now().timestamp(),
            execute_by=None  # Manual escalation
        )

    @staticmethod
    def _generate_latency_ticket(ticket_id: str, anomaly: DetectedAnomaly) -> MitigationTicket:
        """Generate ticket for latency spike."""
        return MitigationTicket(
            ticket_id=ticket_id,
            ticket_type="investigate",
            priority="medium",
            title=f"Latency spike: {anomaly.affected_component}",
            description=f"Execution time exceeded threshold.\n{anomaly.root_cause}",
            related_anomaly_id=anomaly.anomaly_id,
            related_job_id=anomaly.affected_job,
            target_agent="monitoring",
            execution_steps=[
                "1. Check system resource utilization (CPU, memory)",
                "2. Check MCP server responsiveness",
                "3. Review network latency metrics",
                "4. If persistent: trigger auto-scaling or alert ops"
            ],
            created_at=datetime.now().timestamp(),
            execute_by=datetime.now().timestamp() + 60  # Investigate within 60 seconds
        )

    @staticmethod
    def _generate_generic_ticket(ticket_id: str, anomaly: DetectedAnomaly) -> MitigationTicket:
        """Generate generic ticket for unknown anomaly."""
        return MitigationTicket(
            ticket_id=ticket_id,
            ticket_type="escalate",
            priority="high",
            title=f"Anomaly detected: {anomaly.anomaly_type}",
            description=f"Unknown anomaly type.\n{anomaly.root_cause}",
            related_anomaly_id=anomaly.anomaly_id,
            related_job_id=anomaly.affected_job,
            target_agent=None,
            execution_steps=[
                "1. Review anomaly details in logs",
                "2. Understand root cause",
                "3. Determine if auto-remediation or manual intervention needed"
            ],
            created_at=datetime.now().timestamp()
        )


# ============================================================================
# EVENT ROUTING TO IO AGENT
# ============================================================================

class EventRoutingContract:
    """
    Defines how ECA routes mitigation tickets back to IO Agent.
    """

    @staticmethod
    def route_ticket_to_io_agent(
        ticket: MitigationTicket,
        user_request_id: str
    ) -> Dict[str, Any]:
        """
        Send ticket to IO Agent as a system notification/mitigation prompt.
        
        The IO Agent can then:
        1. Add to response context
        2. Prompt user for action
        3. Auto-retry if benign
        4. Escalate if critical
        
        Message format for IO Agent:
        """
        return {
            "type": "mitigation_prompt",
            "severity": ticket.priority,
            "user_request_id": user_request_id,
            "ticket_id": ticket.ticket_id,
            "title": ticket.title,
            "description": ticket.description,
            "message": f"""
            During processing, an issue was detected:
            
            [{ticket.ticket_id}] {ticket.title}
            Priority: {ticket.priority}
            
            {ticket.description}
            
            Recommended Actions:
            {chr(10).join(f'  - {step}' for step in ticket.execution_steps[:3])}
            
            Status: {ticket.status}
            """,
            "auto_remediation": ticket.target_agent is not None,
            "requires_user_action": ticket.target_agent is None
        }


if __name__ == "__main__":
    print("ECA Event Correlation Contract loaded")
    
    # Example: Detect timeout anomaly
    event = KafkaEvent(
        event_id=str(uuid.uuid4()),
        timestamp=datetime.now().timestamp(),
        category="agent-errors",
        severity="error",
        source_agent="geological_scout_001",
        job_id="job_42",
        trace_id="trace_xyz",
        request_id="req_user_001",
        message="MCP tool geological_survey_india timed out after 30 seconds",
        details={
            "mcp_tool": "query_deposits",
            "mcp_server": "geological_mcp",
            "timeout_seconds": 30,
            "execution_time_ms": 31000
        }
    )
    
    # Detect anomaly
    anomaly = AnomalyDetectionRules.apply_rules(event)
    if anomaly:
        print(f"Anomaly detected: {anomaly.anomaly_type}")
        
        # Generate ticket
        ticket = TicketGenerator.generate_ticket(anomaly)
        print(f"Ticket generated: {ticket.ticket_id} (priority: {ticket.priority})")
